### ISSUE TITLE
third_person_terrain not working

### ISSUE THREAD

**Issue by DiegoBM** [armory3d/armory_templates#1]
Hating to be the first one.

Third person terrain is not working with blender 2.8 beta 0.6 after updating to the latest SDK. I get a black screen and infinite runtime errors like this one:

TypeError
at init (krom.js:2488:5)
at iron_App.render (krom.js:6317:5)
at kha_System.render (krom.js:25904:3)
at kha_SystemImpl.renderCallback (krom.js:26029:2)
Uncaught exception:
b.b[i] = p.b[i * 4];

Ironically 0.6beta release does compile and run without runtime errors, but I cannot see any terrain.

(If it helps, the terrain examples don't work either. The other templates and examples seem to work fine)

**Comment by DiegoBM** [comment]
Hating to be the first one.

Third person terrain is not working with blender 2.8 beta after updating to the latest SDK. I get a black screen and infinite runtime errors like this one:

TypeError
   at init (krom.js:2488:5)
   at iron_App.render (krom.js:6317:5)
   at kha_System.render (krom.js:25904:3)
   at kha_SystemImpl.renderCallback (krom.js:26029:2)
Uncaught exception:
                                b.b[i] = p.b[i * 4];


Ironically 0.6beta release does compile and run without runtime errors, but I cannot see any terrain

**Comment by luboslenco** [comment]
Sorry it's too early.:) It may work if you update again (or maybe try to switch to OpenGL in armory add-on preferences if you are on Windows.)

**Comment by DiegoBM** [comment]
Tried both options actually. I have kept it in OpenGL ever since you mentioned that for armory :) , and I have been trying again with every new commit that you released today (even that Krom one), but still not working. In any case I'll stick to that "it's too early" statement. I just got overexcited when I saw it popping up this morning hehehe. The picture in twitter looks incredible in any case!

**Comment by luboslenco** [comment]
Oh I see, will push one more update tonight(in a few hours) and report back, many thanks for testing!

(I will need to point our [Kha](https://github.com/armory3d/Kha) fork to the latest master Kha. The terrain thingy uses new Kha/Krom stuff for reading texture pixels which is then used to construct the terrain physics shape from heightmap).

**Comment by DiegoBM** [comment]
Thank you very much! Looking forward to play with the terrain

**Comment by luboslenco** [comment]
Should be good to go now on Windows with both Direct3D11 and OpenGL. I will also update Krom binaries for Linux & macOS asap. Please let me know if you get to re-test it.

The terrain system is super primitive and various issues will likely popup, but at least there should be a way to walk around some heightmaps now. ⛰⛰⛰Will also add a manual page on terrain with more details.

**Comment by DiegoBM** [comment]
Hi @luboslenco, it seems to be still struggling, but now with a different runtime error:

TypeError
   at kha_Image.prototype.getPixels (krom.js:24743:4)
   at init (krom.js:2507:4)
   at iron_App.render (krom.js:6366:5)
   at kha_System.render (krom.js:26041:3)
   at kha_SystemImpl.renderCallback (krom.js:26167:2)
Uncaught exception:
                        return haxe_io_Bytes.ofData(Krom.getTexturePixels(this.texture_));


Having a terrain system is much more than what other engines (even those which had commercial support like Xenko) can claim, so no shame on that. There is always a beginning for all great things in life (or computing)

**Comment by DiegoBM** [comment]
Actually it works with Direct3D11!! It seems to fail for OpenGL only in Windows (didn't delete the previous message for debugging purposes).

Great stuff!! :D

**Comment by luboslenco** [comment]
(Dammit.. updated opengl binary now.. 😇 )

**Comment by DiegoBM** [comment]
That last one got the prize, working like a charm on both Direct3D11 and OpenGL now! Thank you for your efforts! 😃. Closing as fixed
