### ISSUE TITLE
WebGL, works fine locally (button is fine), runs on GitHub (button is abnormal)

### ISSUE THREAD

**Issue by 958479612** [armory3d/armory_templates#10]
WebGL, works fine locally (button is fine), runs on GitHub (button is abnormal, button is gone)
https://losemry.github.io/web3/

**Comment by rpaladin** [comment]
Closing this issue, as the given link + username + repository is no longer valid or existing, and thus no more information is available. Feel free to update the link or add more information to your post and request the reopeneing of this issue in a new post, if the issue still occurs.
