### ISSUE TITLE
Terrrain / 3rd person demo not initializing properly 

### ISSUE THREAD

**Issue by BluePrintRandom** [armory3d/armory_templates#2]
![image](https://user-images.githubusercontent.com/7190873/52540542-70ca3380-2d3f-11e9-9366-109d953bf4b9.png)

No terrain/ scene elements shown when engine is started.
Armoury_win64_06

**Comment by luboslenco** [comment]
Please check the readme here:
https://github.com/armory3d/armory_templates/blob/master/README.md

(You need to either use git armory version or download the templates release package for the armory version you are using. Terrain requires git armory as it's a new feature.)
