### ISSUE TITLE
Questions about the key binding section in the template

### ISSUE THREAD

**Issue by MrSYSnokia** [armory3d/armory_templates#21]
I don't seem to have found any part of the key binding in the source code for this project. I spent a few days carefully reading the source code, trying to find the implementation method for "WASD" button movement in the project, but found nothing.

Code link:
https://github.com/armory3d/armory_templates/blob/master/first_person/Sources/arm/FirstPersonController.hx

If the author sees this reply, please answer my questions. Thank you

**Comment by rpaladin** [comment]
Hi. The [`FirstPersonColler`](https://github.com/armory3d/armory/blob/main/Sources/armory/trait/FirstPersonController.hx) trait is a child class derived from the parent class, which is the [`CameraController`](https://github.com/armory3d/armory/blob/main/Sources/armory/trait/internal/CameraController.hx) trait. The parent class defines the WASD keybinding. The derivation is done [here](https://github.com/armory3d/armory/blob/main/Sources/armory/trait/FirstPersonController.hx#L10).

**Comment by rpaladin** [comment]
As there has been no further input from you, the OP, and my given answer above seems to be what the OP is looking for, I'm closing this issue. Feel free to continue asking anymore related questions in this issue in the future and we can reopen the issue if needed.
